ALTER TABLE job ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL AFTER apply_count;
ALTER TABLE enterprise ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL AFTER updated_at;
ALTER TABLE user ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL AFTER updated_at;
ALTER TABLE student ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL AFTER updated_at;
ALTER TABLE application ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL AFTER updated_at;
